os: linux
language: ruby
sudo: required
script:
  - pandoc _data/data.yml -o pdf/cv.pdf --template=pdf/template.tex --pdf-engine=xelatex
deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file:
    - "cv.pdf"
  skip_cleanup: true
  on:
    repo: dionisiskon/onlinecv